# DigitalOcean App Platform Specification
# This file defines your app structure and deployment configuration

name: barber-qms-backend
region: nyc

# Database component (if using DO Managed Database)
databases:
  - name: barber-qms-db
    engine: PG
    version: "15"
    size: db-s-1vcpu-1gb  # Adjust based on your needs
    num_nodes: 1
    production: true

# Pre-deploy job for database migrations
jobs:
  - name: db-migrate
    kind: PRE_DEPLOY
    source_dir: /
    github:
      repo: fawad1997/BarberQMSBackend  # Update this
      branch: test-deploy  # or main
    dockerfile_path: Dockerfile
    run_command: alembic upgrade head
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${barber-qms-db.DATABASE_URL}
      - key: ENVIRONMENT
        scope: RUN_AND_BUILD_TIME
        value: production

# Main FastAPI service
services:
  - name: web
    source_dir: /
    github:
      repo: fawad1997/BarberQMSBackend  # Update this
      branch: test-deploy  # or main
    dockerfile_path: Dockerfile
    run_command: uvicorn main:app --host 0.0.0.0 --port 8080
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs  # Adjust based on your needs
    
    # Port configuration
    http_port: 8080
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${barber-qms-db.DATABASE_URL}
      - key: ENVIRONMENT
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: your_secret_key_here  # Replace with a secure secret
      - key: JWT_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: your_jwt_secret_here  # Replace with a secure JWT secret
      # Add other environment variables as needed
      # - key: EMAIL_SMTP_SERVER
      #   scope: RUN_AND_BUILD_TIME
      #   value: smtp.gmail.com
      # - key: EMAIL_SMTP_PORT
      #   scope: RUN_AND_BUILD_TIME
      #   value: "587"

# Static site for any frontend (optional)
# static_sites:
#   - name: frontend
#     github:
#       repo: YOUR_GITHUB_USERNAME/BarberQMSFrontend
#       branch: main
#     build_command: npm run build
#     output_dir: /dist 