"""Updated no of people in appointments

Revision ID: 295ac38707fb
Revises: c164b26e5724
Create Date: 2024-12-20 05:08:10.090167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295ac38707fb'
down_revision: Union[str, None] = 'c164b26e5724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('number_of_people', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'number_of_people')
    # ### end Alembic commands ###
