"""shop model advertisement

Revision ID: 30d12ca5c857
Revises: 847daa7441a8
Create Date: 2024-10-28 22:22:14.869601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d12ca5c857'
down_revision: Union[str, None] = '847daa7441a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('has_advertisement', sa.Boolean(), nullable=True))
    op.add_column('shops', sa.Column('advertisement_image_url', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('advertisement_start_date', sa.DateTime(), nullable=True))
    op.add_column('shops', sa.Column('advertisement_end_date', sa.DateTime(), nullable=True))
    op.add_column('shops', sa.Column('is_advertisement_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'is_advertisement_active')
    op.drop_column('shops', 'advertisement_end_date')
    op.drop_column('shops', 'advertisement_start_date')
    op.drop_column('shops', 'advertisement_image_url')
    op.drop_column('shops', 'has_advertisement')
    # ### end Alembic commands ###
