"""made 24 hour shop

Revision ID: 3dcab5da49c5
Revises: 842dad3f7a91
Create Date: 2025-03-17 09:15:29.045867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dcab5da49c5'
down_revision: Union[str, None] = '842dad3f7a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('is_open_24_hours', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'is_open_24_hours')
    # ### end Alembic commands ###
