"""update_models_for_unified_business_structure

Revision ID: 83847072ac87
Revises: add_timezone_to_shops_manual
Create Date: 2025-06-22 12:11:31.190895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83847072ac87'
down_revision: Union[str, None] = 'add_timezone_to_shops_manual'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
