"""make service_id nullable in queue_entries

Revision ID: 842dad3f7a91
Revises: 928fa08d08d7
Create Date: 2024-12-23 08:24:18.761845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842dad3f7a91'
down_revision: Union[str, None] = '928fa08d08d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue_entries', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue_entries', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
