"""shop model change

Revision ID: 847daa7441a8
Revises: 70976730105f
Create Date: 2024-10-28 07:57:10.330660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847daa7441a8'
down_revision: Union[str, None] = '70976730105f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('address', sa.String(), nullable=False))
    op.add_column('shops', sa.Column('city', sa.String(), nullable=False))
    op.add_column('shops', sa.Column('state', sa.String(), nullable=False))
    op.add_column('shops', sa.Column('zip_code', sa.String(), nullable=False))
    op.add_column('shops', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('shops', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('shops', 'email')
    op.drop_column('shops', 'phone_number')
    op.drop_column('shops', 'zip_code')
    op.drop_column('shops', 'state')
    op.drop_column('shops', 'city')
    op.drop_column('shops', 'address')
    # ### end Alembic commands ###
