"""Add username field to shops table

Revision ID: add_username_to_shops
Revises: b4c5d8019e25
Create Date: 2025-06-04 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_username_to_shops'
down_revision: Union[str, None] = 'b4c5d8019e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: This migration documents the username field addition
    # The field has already been added manually to avoid migration conflicts
    
    # Check if column exists before adding (in case it was already added manually)
    conn = op.get_bind()
    result = conn.execute(sa.text("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name = 'shops' AND column_name = 'username'
    """))
    
    if not result.fetchone():
        op.add_column('shops', sa.Column('username', sa.String(), nullable=True))
        op.create_index(op.f('ix_shops_username'), 'shops', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shops_username'), table_name='shops')
    op.drop_column('shops', 'username')
    # ### end Alembic commands ###
