"""Updated Shop Hours

Revision ID: c164b26e5724
Revises: f817499aaaf8
Create Date: 2024-11-27 02:32:33.190179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c164b26e5724'
down_revision: Union[str, None] = 'f817499aaaf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('opening_time', sa.Time(), nullable=False))
    op.add_column('shops', sa.Column('closing_time', sa.Time(), nullable=False))
    op.drop_column('shops', 'operating_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('operating_hours', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('shops', 'closing_time')
    op.drop_column('shops', 'opening_time')
    # ### end Alembic commands ###
