"""slug added, shop duration table added, custom price option added

Revision ID: ee20217de0b5
Revises: 3dcab5da49c5
Create Date: 2025-04-12 20:20:04.649055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee20217de0b5'
down_revision: Union[str, None] = '3dcab5da49c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('custom_duration', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('custom_price', sa.Float(), nullable=True))
    op.add_column('queue_entries', sa.Column('custom_duration', sa.Integer(), nullable=True))
    op.add_column('queue_entries', sa.Column('custom_price', sa.Float(), nullable=True))
    op.add_column('shops', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_shops_slug'), 'shops', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shops_slug'), table_name='shops')
    op.drop_column('shops', 'slug')
    op.drop_column('queue_entries', 'custom_price')
    op.drop_column('queue_entries', 'custom_duration')
    op.drop_column('appointments', 'custom_price')
    op.drop_column('appointments', 'custom_duration')
    # ### end Alembic commands ###
