"""added username

Revision ID: f7db13e6fc1b
Revises: 8310e0ff1a7f
Create Date: 2025-06-04 22:22:12.001613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7db13e6fc1b'
down_revision: Union[str, None] = '8310e0ff1a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('barber_schedules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('barber_schedules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('barber_schedules_barber_id_fkey', 'barber_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'barber_schedules', 'barbers', ['barber_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'barber_schedules', type_='foreignkey')
    op.create_foreign_key('barber_schedules_barber_id_fkey', 'barber_schedules', 'barbers', ['barber_id'], ['id'])
    op.drop_column('barber_schedules', 'updated_at')
    op.drop_column('barber_schedules', 'created_at')
    op.alter_column('appointments', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
